/* Green Wing — global site constants (single source of truth) */
window.GW_SITE = {
  name: 'Green Wing Energy Solutions',
  phone: '07942 860052',
  phoneTel: '+447942860052',
  email: 'joncullum@greenwinguk.com',
  address: "149 Capstone Road | Bournemouth | Dorset | BH8 8RZ",
  addressHtml: "149 Capstone Road<br>Bournemouth<br>Dorset<br>BH8 8RZ",
  mapsQuery: "149 Capstone Road, Bournemouth, Dorset BH8 8RZ",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=149+Capstone+Road,+Bournemouth,+Dorset,+BH8+8RZ",
  url: 'https://greenwingenergysolutions.com',
  tagline: 'Energy saving solutions that don\'t cost the Earth.',
  positioning: 'We find the hidden energy waste in commercial buildings, prioritise the fixes, and prove the savings.',
  ctaPrimary: 'Arrange an Energy Review',
  ctaSecondary: 'Request a Sample Report',
  companyNumber: '6981538',
  companiesHouseUrl: 'https://find-and-update.company-information.service.gov.uk/company/6981538',
  registeredOffice: '149, Capstone Road, Bournemouth, Dorset, BH8 8RZ',
  foundingDate: '2009',
  responseTime: 'We aim to reply within one working day.',
  contactEndpoint: '/.netlify/functions/contact',
  gaMeasurementId: 'G-RGKJRGPLZZ',
  defaultOgImage: '/assets/images/hm-pg-bkgrd-img.jpg',
  social: {
    facebook: 'https://www.facebook.com/greenwingenergysolutions',
    linkedin: 'https://www.linkedin.com/company/green-wing-energy-solutions',
    instagram: 'https://www.instagram.com/greenwingenergysolutions',
  },
  seo: {
    'about.html': {
      title: 'About Green Wing Energy Solutions',
      description: 'Independent commercial energy optimisation consultancy since 2009. Measure first, recommend second — honest about what is worth doing on UK multi-site estates.',
      path: '/about',
      image: '/assets/images/about-us-main-img-1.jpg',
    },
    'services.html': {
      title: 'Commercial Energy Services | Green Wing Energy Solutions',
      description: 'Onsite Discovery Assessment, Discovery Assessment Report and Roadmap, and Energy Optimisation as a Service — a clear path from finding waste to proving savings.',
      path: '/services',
      image: '/assets/images/discovery-assessment-lobby.jpg',
    },
    'solutions.html': {
      title: 'Energy Solutions & Technologies | Green Wing Energy Solutions',
      description: 'Technologies we assess when site conditions suit — refrigeration optimisation, voltage optimisation, FilterPro, EndoTherm, LED lighting and more.',
      path: '/solutions',
      image: '/assets/images/solutions-main-img-2.jpg',
    },
    'case-studies.html': {
      title: 'Results & Case Studies | Green Wing Energy Solutions',
      description: 'Real sites, real measurement. Outcomes from commercial energy optimisation across hospitality, leisure and manufacturing.',
      path: '/case-studies',
      image: '/assets/images/reporting-tool-backgrd.jpg',
    },
    'referrals.html': {
      title: 'Referrals & Endorsements | Green Wing Energy Solutions',
      description: 'Most Green Wing work starts with a recommendation. Learn why operators, site teams and partners refer our evidence-led energy optimisation approach.',
      path: '/referrals',
      image: '/assets/images/green-wing-logo-full-colour.svg',
    },
    'contact.html': {
      title: 'Contact | Green Wing Energy Solutions',
      description: 'Tell us about your estate and we will arrange an energy review. Call 07942 860052 or email joncullum@greenwinguk.com',
      path: '/contact',
      image: '/assets/images/greenwing-wing-logo.jpg',
    },
    'insights.html': {
      title: 'Insights | Green Wing Energy Solutions',
      description: 'Practical thinking on commercial energy — what actually moves the needle, and how to prove it.',
      path: '/insights',
      image: '/assets/images/hm-pg-audit-img-1.jpg',
    },
    'onsite-discovery-assessment.html': {
      title: 'Onsite Discovery Assessment | Green Wing Energy Solutions',
      description: 'The fastest way to see what your energy bills cannot show — a structured site visit inspecting plant, controls and daily routines.',
      path: '/onsite-discovery-assessment',
      image: '/assets/images/discovery-assessment-site.png',
    },
    'discovery-roadmap.html': {
      title: 'Discovery Assessment Report and Roadmap | Green Wing Energy Solutions',
      description: 'Your discovery findings written up as a clear Discovery Assessment Report and Roadmap — every opportunity scored by savings, payback and measurement method.',
      path: '/discovery-roadmap',
      image: '/assets/images/pdf-report-example.jpg',
    },
    'eoaas.html': {
      title: 'Energy Optimisation as a Service | Green Wing Energy Solutions',
      description: 'Make lower energy spend a monthly discipline — ongoing review, prioritised recommendations, reporting and savings verification.',
      path: '/eoaas',
      image: '/assets/images/reporting-tool-backgrd.jpg',
    },
    'terms-and-policies.html': {
      title: 'Terms and Policies | Green Wing Energy Solutions',
      description: 'Privacy Policy, Terms of Use, and Cookie Policy for Green Wing Energy Solutions.',
      path: '/terms-and-policies',
      image: '/assets/images/green-wing-logo-full-colour.svg',
    },
    'insights/refrigeration-runs-24-7.html': {
      title: 'Why your refrigeration runs 24/7 | Green Wing Insights',
      description: 'Most commercial kitchens run refrigeration on schedules set years ago. What a discovery visit typically finds — and how to fix it.',
      path: '/insights/refrigeration-runs-24-7',
      image: '/assets/images/hm-pg-audit-img-1.jpg',
    },
    'insights/roadmap-vs-audit.html': {
      title: 'Energy audit vs Discovery Assessment Report and Roadmap | Green Wing Insights',
      description: 'What is the difference between an energy audit and a Discovery Assessment Report and Roadmap? One produces a document — the other produces decisions.',
      path: '/insights/roadmap-vs-audit',
      image: '/assets/images/pdf-report-example.jpg',
    },
    'insights/proving-savings.html': {
      title: 'How to prove energy savings | Green Wing Insights',
      description: 'Baseline, measurement route, and site context — the three things that make a savings figure credible to your finance team.',
      path: '/insights/proving-savings',
      image: '/assets/images/reporting-tool-backgrd.jpg',
    },
    'insights/scope-1-2-3.html': {
      title: 'Scope 1, 2 and 3 emissions explained | Green Wing Insights',
      description: 'What Scope 1, 2 and 3 mean for commercial operators — and where on-site energy optimisation fits in your carbon reporting.',
      path: '/insights/scope-1-2-3',
      image: '/assets/images/commercial-img-1.jpg',
    },
  },
};
